# Generated by Django 5.1 on 2024-08-25 01:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('file', models.FileField(upload_to='sermon_uploads', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['flac', 'ogg', 'mp3', 'wav'])], verbose_name='Sermon File')),
                ('thumbnail', models.ImageField(upload_to='sermon_thumbnails', verbose_name='Sermon Thumbnail')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
    ]
