# Generated by Django 5.1 on 2024-08-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='slug',
            field=models.SlugField(editable=False, verbose_name='Slug'),
        ),
    ]
