# Generated by Django 5.1 on 2024-08-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermon', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
