# Generated by Django 5.1 on 2024-08-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermon', '0007_review_sermon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='slug',
            field=models.SlugField(editable=False, unique=True, verbose_name='Slug'),
        ),
    ]
